version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=PowerPlants!StrongPassword123
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1433"]
      interval: 10s
      retries: 10
      start_period: 30s


  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: powerplants-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PowerPlantsDb;User Id=sa;Password=PowerPlants!StrongPassword123;TrustServerCertificate=True;Encrypt=False;
    ports:
      - "5000:8080"

volumes:
  sqldata: